config/routes.rb
Rails.application.routes.draw do
  resources :records
  root to: "main#index"
  get 'hello/index'
  get "/", to: "main#index"

  get "add_record", to: "records#new"
  post "add_record", to: "records#create"

  get "records/:id", to: "records#show", as: :show
  post "records/:id", to: "records#destroy"

  get "update", to: "main#update"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
    serialize :json_data
    validates :cadnumber, presence: true, uniqueness: true, format: { with: /\d{2}[:]\d{2}[:]\d{6,7}:\d+\z/, message: "must be a valid" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index; end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    before_action :set_records, only: %i[index update]

    def index
    end

    def update
        @records.each do |record|
            #uri = URI.parse("https://rosreestr.gov.ru/fir_lite_rest/api/gkn/fir_object/#{record.cadnumber}")
            #response = Net::HTTP.get_response(uri)
            #p response
            response = {"objectId":"54:32:010641:12","type":"parcel","regionKey":154,"source":1,"firActualDate":"2022-02-14","objectData":{"id":"54:32:10641:12","regionKey":154,"srcObject":1,"objectType":"002001001000","objectName":"01","removed":0,"dateLoad":"2022-02-14","addressNote":"обл. Новосибирская, г. Бердск, садоводческий потребительский кооператив \"Восток-1\", улица Железнодорожная, 73","objectCn":"54:32:010641:12","rsCode":"54.0.2.1","actualDate":"2022-02-14","brkStatus":-1,"objectAddress":{"id":"54:32:10641:12","regionKey":154,"okato":"50408000000","kladr":"5400000200000","region":"54","place":"Бердск","placeType":"г","addressNotes":"обл. Новосибирская, г. Бердск, садоводческий потребительский кооператив \"Восток-1\", улица Железнодорожная, 73","mergedAddress":"г Бердск"}},"parcelData":{"id":"54:32:10641:12","regionKey":154,"parcelCn":"54:32:010641:12","parcelStatus":"01","dateCreate":"2003-12-08","categoryType":"003002000000","areaValue":398.0,"areaType":"009","areaUnit":"055","rightsReg":true,"cadCost":77784.36,"cadUnit":"383","dateCost":"2021-01-01","oksFlag":0,"oksInventoryCost":0.0,"utilCode":"141004000000","utilByDoc":"Для ведения садоводства и огородничества"}}
            if response != record.json_data
                record.cadnumber = response[:objectId].to_s
                record.json_data = response
                record.save
                redirect_to root_path, alert: 'Update has changes, request is required'
            else
                redirect_to root_path, notice: 'Records\' update has no changes'
            end
        end
    end

    private

    def set_records
        @records = Record.all
    end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
    before_action :set_record, only: %i[show destroy]

    def new
        @record = Record.new
    end

    def create
        #uri = URI.parse("https://rosreestr.gov.ru/fir_lite_rest/api/gkn/fir_object/#{@record.cadnumber}")
        #response = Net::HTTP.get_response(uri)
        #p response
        response = {"objectId":"54:32:10641:12","type":"parcel","regionKey":154,"source":1,"firActualDate":"2022-02-14","objectData":{"id":"54:32:10641:12","regionKey":154,"srcObject":1,"objectType":"002001001000","objectName":"01","removed":0,"dateLoad":"2022-02-14","addressNote":"обл. Новосибирская, г. Бердск, садоводческий потребительский кооператив \"Восток-1\", улица Железнодорожная, 73","objectCn":"54:32:010641:12","rsCode":"54.0.2.1","actualDate":"2022-02-14","brkStatus":-1,"objectAddress":{"id":"54:32:10641:12","regionKey":154,"okato":"50408000000","kladr":"5400000200000","region":"54","place":"Бердск","placeType":"г","addressNotes":"обл. Новосибирская, г. Бердск, садоводческий потребительский кооператив \"Восток-1\", улица Железнодорожная, 73","mergedAddress":"г Бердск"}},"parcelData":{"id":"54:32:10641:12","regionKey":154,"parcelCn":"54:32:010641:12","parcelStatus":"01","dateCreate":"2003-12-08","categoryType":"003002000000","areaValue":398.0,"areaType":"009","areaUnit":"055","rightsReg":true,"cadCost":77784.36,"cadUnit":"383","dateCost":"2021-01-01","oksFlag":0,"oksInventoryCost":0.0,"utilCode":"141004000000","utilByDoc":"Для ведения садоводства и огородничества"}}
        @record = Record.new(record_params)
        @record.json_data = response
        if @record.save
            redirect_to root_path, notice: 'Record created successfully'
        else
            render :new, alert: 'Object save error'
        end
    end

    def show
    end

    def destroy
        @record.destroy
        redirect_to root_path, notice: 'Load was successfully deleted'
    end

    private

    def set_record
        @record = Record.find(params[:id])
    end

    def record_params
        params.require(:record).permit(:cadnumber)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/hello/index.html.erb
<h1>Hello World</h1>
<p>Find me in app/views/hello/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Records</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://www.kryogenix.org/code/browser/sorttable/sorttable.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <div class="container">
      <%= render partial: "shared/flash" %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/main/index.html.erb
<p></p>
<div class= "d-flex justify-content-center"><h1>Records</h1></div>

<table class="sortable">
  <thead>
    <tr>
      <th><div class= "d-flex justify-content-center text-truncate">Cadastrial number</div></th>
      <th><div class= "d-flex justify-content-center">Address</div></th>
      <th><div class= "d-flex justify-content-center">Updated at</div></th>
      <th colspan="1"></th>
    </tr>
  </thead>
<p></p>
  <tbody>
    <% @records.each do |record| %>
      <tr>
        <td><%= record.cadnumber %></td>
        <td><%= record.json_data[:objectData][:addressNote] %></td>
        <td><%= record.updated_at %></td>
        <td>
          <%= link_to "Show", record %>
          <%= link_to "Delete", record, method: :destroy, data: { confirm: 'Are you sure?' } %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/records/new.html.erb
<p></p>
<div class= "d-flex align-items-center justify-content-center"><h1>Adding a new record</h1></div>
<p></p>
<div class= "d-flex align-items-center justify-content-center">
<%= form_with model: @record, url: add_record_path do |form| %>
    <% if @record.errors.any? %>
        <div class="alert alert-danger">
        <% @record.errors.full_messages.each do |message| %>
            <div><%= message %></div>
        <% end %>
        </div>
    <% end %>
    <%= form.label :cadastrial_number %>
    <%= form.text_field :cadnumber, placeholder: "54:32:0010641:12" %>
    <%= form.submit "Add record" %>
<% end %>
</div>

app/views/records/show.html.erb
<p></p>
<div class= "d-flex justify-content-center"><h1>Record <%= @record.json_data[:objectData][:objectCn] %></h1></div>
<p></p>

<dl class="row">
  <dt class="col-sm-4">Load date</dt>
  <dd class="col-sm-8"><%= @record.json_data[:firActualDate] %></dd>
    
  <dt class="col-sm-4">Cadastrial number</dt>
  <dd class="col-sm-8"><%= @record.json_data[:objectData][:objectCn] %></dd>

  <dt class="col-sm-4">Creation cad.number date</dt>
  <dd class="col-sm-8"><%= @record.json_data[:parcelData][:dateCreate] %></dd>

  <dt class="col-sm-4">Region</dt>
  <dd class="col-sm-8"><%= @record.json_data[:objectData][:objectAddress][:region] %></dd>

  <dt class="col-sm-4">Address</dt>
  <dd class="col-sm-8"><%= @record.json_data[:objectData][:addressNote] %></dd>

  <dt class="col-sm-4">Area</dt>
  <dd class="col-sm-8"><%= @record.json_data[:parcelData][:areaValue] %> кв. м</dd>

  <dt class="col-sm-4">Cadastrial value, rub</dt>
  <dd class="col-sm-8"><%= @record.json_data[:parcelData][:cadCost] %></dd>

  <dt class="col-sm-4">Permitted issues</dt>
  <dd class="col-sm-8"><%= @record.json_data[:parcelData][:utilByDoc] %></dd>
</dl>
<div class= "d-flex justify-content-end">  <%= link_to "Back", root_url %></div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-success mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="nav justify-content-center">
  <a class="nav-link" href="/">Home</a>
  <a class="nav-link" href="/add_record">Add a record</a>  
  <a class="nav-link" href="/update">Check updates</a>    
</nav>